### ISSUE TITLE
GROUND: Telemetry Health

### ISSUE THREAD

**Issue by JateNensvold** [CougsInSpace/CougSat1-Software#1]
Power gui
temp gui
attitude gui

**Comment by WattsUp** [comment]
Wait on #27 before continuing. The packets are changing

**Comment by kennetheversole** [comment]
Do we plan on having a UX review on this?

**Comment by WattsUp** [comment]
Nate is one issue away from a pull request. We will have a review of it then (code, UI, UX, etc.)
