### ISSUE TITLE
ADCS: Research H-Bridge datasheet

### ISSUE THREAD

**Issue by phillip-whitworth** [CougsInSpace/CougSat1-Software#257]
this leads into """ADCS: Design Magnetorquer Class #17"""

Determine the pins used, frequency of transmissions, type of signal needed to control the current flow.

**Comment by phillip-whitworth** [comment]
this is completed.  not sure what we should do to close it.  We are starting on the design now

**Comment by WattsUp** [comment]
Just answer the questions asked in the issue and close it.

**Comment by jlung21** [comment]
Pins used for logic: 
Pin 5 - IN1 
Pin 6 - IN2 
Pin 7 -nSleep

Other pins:

Pin 1 - Vm (Motor power supply)
Pin 2 - Output 1
Pin 3 - Output 2
Pin 4 - GND
Pin 8 - Vcc (Logic power supply)


Externally Applied PWM Frequency Conditions 0 - 250 kHz (Min - Max) According to manufacturer

Logic inputs take a range of 0 - 5.5 V (Min - Max) According to manufacturer

Current can be controlled by applying the PWM frequency range listed above to the IN1, and IN2 logic inputs. nSleep functions as the enable signal.
