### ISSUE TITLE
GROUND: GUI Power - Layer 7

### ISSUE THREAD

**Issue by WattsUp** [CougsInSpace/CougSat1-Software#56]

**Comment by WattsUp** [comment]
Includes overlaying the information on the EPS schematic to show where the energy is flowing

**Comment by kennetheversole** [comment]
I am quite curious about this. Are you saying we could possibly have a some whag live view of the power onboard?

**Comment by WattsUp** [comment]
I want this:![image.png](https://images.zenhubusercontent.com/5b4ee30aa8d8be5bda393b96/892e31cb-e636-439a-8236-287026c203e9)

**Comment by kennetheversole** [comment]
That would be quite nice to have.

**Comment by WattsUp** [comment]
This is done, being reviewed in #328

**Comment by WattsUp** [comment]
![image](https://user-images.githubusercontent.com/13396764/67254963-a24ddf80-f434-11e9-9013-2c2b38aa7c88.png)
